export const FETCH_TOP_RATED_PRODUCTS = 'FETCH_TOP_RATED_PRODUCTS';
export const FETCH_LATEST_PRODUCTS = 'FETCH_LATEST_PRODUCTS';
export const FETCH_VALUE_FOR_MONEY_PRODUCTS = 'FETCH_VALUE_FOR_MONEY_PRODUCTS';
