// PRODUCTS API CALLS
export const FETCH_TOP_RATED_PRODUCTS = 'FETCH_TOP_RATED_PRODUCTS';
export const FETCH_LATEST_PRODUCTS = 'FETCH_LATEST_PRODUCTS';
export const FETCH_VALUE_FOR_MONEY_PRODUCTS = 'FETCH_VALUE_FOR_MONEY_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';

// CART ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART';

// FOR CLEARING STATES
export const CLEAR_PRODUCT_STATE = 'CLEAR_PRODUCT_STATE';

// FOR ERRORS AND FAIL REQUESTS

export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
